version: '2'
services:
    jhipsterapptruequeo-app:
        image: jhipsterapptruequeo
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsterapptruequeo-postgresql:5432/jhipsterapptruequeo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterapptruequeo-postgresql:
        extends:
            file: postgresql.yml
            service: jhipsterapptruequeo-postgresql
